[package]
name = "fpe"
version = "0.0.0"
authors = ["Jack Grigg <str4d@i2pmail.org>"]
license = "MIT/Apache-2.0"

description = "Format-preserving encryption"
documentation = "https://docs.rs/fpe/"
homepage = "https://github.com/str4d/fpe"
repository = "https://github.com/str4d/fpe"

[dependencies]
